Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  CountComments: false
  Max: 15

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
