---
base:
  build: .
  volumes:
    - ".:/app"
  environment:
    ROBOT_ENV: development

basetest:
  build: .
  volumes:
    - ".:/app"
  environment:
    ROBOT_ENV: test


app:
  extends:
    file: docker-compose.yml
    service: base
  command: ./bin/run

test:
  extends:
    file: docker-compose.yml
    service: basetest
  entrypoint: ['bundle', 'exec', 'rake']

rspec:
  extends:
    file: docker-compose.yml
    service: basetest
  entrypoint: ['bundle', 'exec', 'rspec']
