version: '3.4'

services:
  app:
    build: .
    volumes:
      - ".:/app"
    command: ./bin/run

  test:
    build: .
    volumes:
      - ".:/app"
    environment:
      APP_ENV: test
    entrypoint: ['bundle', 'exec', 'rake']

  rspec:
    build: .
    volumes:
      - ".:/app"
    environment:
      APP_ENV: test
    entrypoint: ['bundle', 'exec', 'rspec']
