version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker info
      - run: docker build -t dmuso/toyrobot .
      - run: docker run -e ROBOT_ENV=test dmuso/toyrobot bundle exec rake
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push dmuso/toyrobot
